// Generated by backend/scripts/generate_credits.py from backend/samples/public/CREDITS.md. Do not edit by hand.

export type Credit = {
  file: string;
  author: string;
  license: string;
  source: string;
};

export const CREDITS: Credit[] = [
  {
    "file": "File:Tree Sapling in British Columbia, Canada 2019.jpg",
    "author": "Ben Hemmings",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Tree_Sapling_in_British_Columbia,_Canada_2019.jpg"
  },
  {
    "file": "File:Mangrove plantation.jpg",
    "author": "User:T.saris",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Mangrove_plantation.jpg"
  },
  {
    "file": "File:Flooded Albizia Saman (rain tree) in the Mekong.jpg",
    "author": "Basile Morin",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Flooded_Albizia_Saman_(rain_tree)_in_the_Mekong.jpg"
  },
  {
    "file": "File:Road construction vehicle, Bangalore (2025).jpg",
    "author": "Gpkp",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Road_construction_vehicle,_Bangalore_(2025).jpg"
  },
  {
    "file": "File:Road construction in tea plantation JEG9546.jpg",
    "author": "PJeganathan",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Road_construction_in_tea_plantation_JEG9546.jpg"
  },
  {
    "file": "File:Field of Solar Panels near Ogwell.jpg",
    "author": "Partonez",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Field_of_Solar_Panels_near_Ogwell.jpg"
  },
  {
    "file": "File:Solar panel field works near Gitit2940.jpg",
    "author": "\u05d9\u05e2\u05e7\u05d1",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Solar_panel_field_works_near_Gitit2940.jpg"
  },
  {
    "file": "File:Solar panel field works near Gitit2941.jpg",
    "author": "\u05d9\u05e2\u05e7\u05d1",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Solar_panel_field_works_near_Gitit2941.jpg"
  },
  {
    "file": "File:A classroom of children from rural homes.jpg",
    "author": "Royal Mayhem",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:A_classroom_of_children_from_rural_homes.jpg"
  },
  {
    "file": "File:A beautiful hand pump in village Bado, Sindh.jpg",
    "author": "\u0645\u06be\u062a\u0627\u0628 \u0627\u062d\u0645\u062f",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:A_beautiful_hand_pump_in_village_Bado,_Sindh.jpg"
  },
  {
    "file": "File:Quibdo Garbage dump.jpg",
    "author": "Mussi Katz",
    "license": "CC0",
    "source": "https://commons.wikimedia.org/wiki/File:Quibdo_Garbage_dump.jpg"
  },
  {
    "file": "File:Volunteers participate in beach debris cleanup - 52752007055.jpg",
    "author": "CapeHatterasNPS",
    "license": "Public domain",
    "source": "https://commons.wikimedia.org/wiki/File:Volunteers_participate_in_beach_debris_cleanup_-_52752007055.jpg"
  },
  {
    "file": "File:California Drought Dry Lakebed 2009.jpg",
    "author": "National Oceanic and Atmospheric Administration",
    "license": "Public domain",
    "source": "https://commons.wikimedia.org/wiki/File:California_Drought_Dry_Lakebed_2009.jpg"
  },
  {
    "file": "File:Deforested area, Goldisthal, 2023-05-20.jpg",
    "author": "Radomianin",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Deforested_area,_Goldisthal,_2023-05-20.jpg"
  },
  {
    "file": "File:Tree stump with oak sapling at Myrstigen 1.jpg",
    "author": "W.carter",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Tree_stump_with_oak_sapling_at_Myrstigen_1.jpg"
  },
  {
    "file": "File:Tree stump with oak sapling at Myrstigen 2.jpg",
    "author": "W.carter",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Tree_stump_with_oak_sapling_at_Myrstigen_2.jpg"
  },
  {
    "file": "File:Ficus religiosa sapling planted on tree Photo 24.jpg",
    "author": "Rohitjahnavi",
    "license": "CC BY 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Ficus_religiosa_sapling_planted_on_tree_Photo_24.jpg"
  },
  {
    "file": "File:Dr. Babasaheb Ambedkar planting a sapling of Bodhi tree (Pipal Tree) in the campus of Milind College, Aurangabad.jpg",
    "author": "Unknown author",
    "license": "Public domain",
    "source": "https://commons.wikimedia.org/wiki/File:Dr._Babasaheb_Ambedkar_planting_a_sapling_of_Bodhi_tree_(Pipal_Tree)_in_the_campus_of_Milind_College,_Aurangabad.jpg"
  },
  {
    "file": "File:Tree sapling at Madison Parish Courthouse.jpg",
    "author": "Ktkvtsh",
    "license": "CC BY 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Tree_sapling_at_Madison_Parish_Courthouse.jpg"
  },
  {
    "file": "File:Mangrove Plantation in Sundarbans.jpg",
    "author": "Samyuctha",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Mangrove_Plantation_in_Sundarbans.jpg"
  },
  {
    "file": "File:Young mangrove plantation in the Indus Delta.jpg",
    "author": "Agha Tahir Hussain",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Young_mangrove_plantation_in_the_Indus_Delta.jpg"
  },
  {
    "file": "File:Mangrove plantation at Emirates Marine Reserve Dubai.jpg",
    "author": "Lxs",
    "license": "CC BY 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Mangrove_plantation_at_Emirates_Marine_Reserve_Dubai.jpg"
  },
  {
    "file": "File:Immuki Island Mangrove Plantation.jpg",
    "author": "Redgrey08",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Immuki_Island_Mangrove_Plantation.jpg"
  },
  {
    "file": "File:PXL 20250518 070423311.MP Hingalganj mangrove plantation Sundarbans and People and River Icchamati 04.jpg",
    "author": "Sourabh.biswas003",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:PXL_20250518_070423311.MP_Hingalganj_mangrove_plantation_Sundarbans_and_People_and_River_Icchamati_04.jpg"
  },
  {
    "file": "File:Cambridgeshire floods - part flooded road at Fen Drayton village - geograph.org.uk - 7903369.jpg",
    "author": "Peter S",
    "license": "CC BY-SA 2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Cambridgeshire_floods_-_part_flooded_road_at_Fen_Drayton_village_-_geograph.org.uk_-_7903369.jpg"
  },
  {
    "file": "File:Main road in village Herwad affected by flood.jpg",
    "author": "\u0935\u0930\u094d\u0937\u093e \u0926\u0947\u0936\u092a\u093e\u0902\u0921\u0947",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Main_road_in_village_Herwad_affected_by_flood.jpg"
  },
  {
    "file": "File:Longford village flooding on Tewkesbury Road (A38) - geograph.org.uk - 502922.jpg",
    "author": "Nicholas Mutton",
    "license": "CC BY-SA 2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Longford_village_flooding_on_Tewkesbury_Road_(A38)_-_geograph.org.uk_-_502922.jpg"
  },
  {
    "file": "File:Flood waters flooding the village-nearby roads in Fatehabad District; 2023.jpg",
    "author": "Hemish",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Flood_waters_flooding_the_village-nearby_roads_in_Fatehabad_District;_2023.jpg"
  },
  {
    "file": "File:Flood waters reaching the village roads in Fatehabad District; 2023.jpg",
    "author": "Hemish",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Flood_waters_reaching_the_village_roads_in_Fatehabad_District;_2023.jpg"
  },
  {
    "file": "File:Construction work on the A4104 - geograph.org.uk - 6004862.jpg",
    "author": "Philip Halling",
    "license": "CC BY-SA 2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Construction_work_on_the_A4104_-_geograph.org.uk_-_6004862.jpg"
  },
  {
    "file": "File:Road construction Elliot Street downtown Brattleboro VT August 2025 02.jpg",
    "author": "Artaxerxes",
    "license": "CC BY 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Road_construction_Elliot_Street_downtown_Brattleboro_VT_August_2025_02.jpg"
  },
  {
    "file": "File:Road construction Elliot Street downtown Brattleboro VT August 2025 01.jpg",
    "author": "Artaxerxes",
    "license": "CC BY 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Road_construction_Elliot_Street_downtown_Brattleboro_VT_August_2025_01.jpg"
  },
  {
    "file": "File:Utilities work on Leeman Road - geograph.org.uk - 8213393.jpg",
    "author": "DS Pugh",
    "license": "CC BY-SA 2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Utilities_work_on_Leeman_Road_-_geograph.org.uk_-_8213393.jpg"
  },
  {
    "file": "File:Road construction in the mountains of Kashmir.jpg",
    "author": "Sanu N",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Road_construction_in_the_mountains_of_Kashmir.jpg"
  },
  {
    "file": "File:Nyngan Solar Plant Photo.jpg",
    "author": "DiamondIIIXX",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Nyngan_Solar_Plant_Photo.jpg"
  },
  {
    "file": "File:East Devon , Solar Panel Farm - geograph.org.uk - 3946973.jpg",
    "author": "Lewis Clarke",
    "license": "CC BY-SA 2.0",
    "source": "https://commons.wikimedia.org/wiki/File:East_Devon_,_Solar_Panel_Farm_-_geograph.org.uk_-_3946973.jpg"
  },
  {
    "file": "File:Solar Panel Farm.jpg",
    "author": "TheUltimateGrass",
    "license": "CC0",
    "source": "https://commons.wikimedia.org/wiki/File:Solar_Panel_Farm.jpg"
  },
  {
    "file": "File:Solar panels at Cowdown Solar Farm - geograph.org.uk - 7426019.jpg",
    "author": "Oscar Taylor",
    "license": "CC BY-SA 2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Solar_panels_at_Cowdown_Solar_Farm_-_geograph.org.uk_-_7426019.jpg"
  },
  {
    "file": "File:Solar panels at Asfordby B Solar Farm - geograph.org.uk - 5925158.jpg",
    "author": "Andrew Tatlow",
    "license": "CC BY-SA 2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Solar_panels_at_Asfordby_B_Solar_Farm_-_geograph.org.uk_-_5925158.jpg"
  },
  {
    "file": "File:Rural school children, San Augustine County1a35426v.jpg",
    "author": "John Vachon",
    "license": "Public domain",
    "source": "https://commons.wikimedia.org/wiki/File:Rural_school_children,_San_Augustine_County1a35426v.jpg"
  },
  {
    "file": "File:Children in rural school.jpg",
    "author": "Mark Knobil",
    "license": "CC BY 2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Children_in_rural_school.jpg"
  },
  {
    "file": "File:Rural school children. San Augustine County, Texas, April 1943.jpg",
    "author": "John Vachon",
    "license": "Public domain",
    "source": "https://commons.wikimedia.org/wiki/File:Rural_school_children._San_Augustine_County,_Texas,_April_1943.jpg"
  },
  {
    "file": "File:Education of Children in Guatemala.JPG",
    "author": "Annkat22",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Education_of_Children_in_Guatemala.JPG"
  },
  {
    "file": "File:Rural school girl, San Augustine County, Texas1a35423v.jpg",
    "author": "John Vachon",
    "license": "Public domain",
    "source": "https://commons.wikimedia.org/wiki/File:Rural_school_girl,_San_Augustine_County,_Texas1a35423v.jpg"
  },
  {
    "file": "File:Water pump 1-2.jpg",
    "author": "Taken by Daniel Schwen Reworked (cropped etc.) by Ralf Roletschek (talk)",
    "license": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Water_pump_1-2.jpg"
  },
  {
    "file": "File:Water pump, Vienna ( 1060223).jpg",
    "author": "Matti Blume",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Water_pump,_Vienna_(_1060223).jpg"
  },
  {
    "file": "File:Hand Water-pump - geograph.org.uk - 1122598.jpg",
    "author": "ronnie leask",
    "license": "CC BY-SA 2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Hand_Water-pump_-_geograph.org.uk_-_1122598.jpg"
  },
  {
    "file": "File:.Hand water pump.jpg",
    "author": "Khoshhat",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:.Hand_water_pump.jpg"
  },
  {
    "file": "File:Old water hand pump - geograph.org.uk - 335071.jpg",
    "author": "Ken Fitlike",
    "license": "CC BY-SA 2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Old_water_hand_pump_-_geograph.org.uk_-_335071.jpg"
  },
  {
    "file": "File:Garbage dump site in Ikot Oduot, Ibesikpo.jpg",
    "author": "Kuuzy",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Garbage_dump_site_in_Ikot_Oduot,_Ibesikpo.jpg"
  },
  {
    "file": "File:Garbage dump at Uyo.jpg",
    "author": "Andikan Efiok Eduok",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Garbage_dump_at_Uyo.jpg"
  },
  {
    "file": "File:Garbage dump 294A0064 S\u00e3o Vicente.jpg",
    "author": "Christian Pirkl",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Garbage_dump_294A0064_S%C3%A3o_Vicente.jpg"
  },
  {
    "file": "File:Garbage dump 294A0043 S\u00e3o Vicente.jpg",
    "author": "Christian Pirkl",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Garbage_dump_294A0043_S%C3%A3o_Vicente.jpg"
  },
  {
    "file": "File:Garbage dump 294A0062 S\u00e3o Vicente.jpg",
    "author": "Christian Pirkl",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Garbage_dump_294A0062_S%C3%A3o_Vicente.jpg"
  },
  {
    "file": "File:Oregon-spring-beach-cleanup-projects-by-ocean-blue-project.jpg",
    "author": "Ocean Blue Project, Inc.",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Oregon-spring-beach-cleanup-projects-by-ocean-blue-project.jpg"
  },
  {
    "file": "File:Oregon-beach-cleanup-ocean-blue-project-volunteers.jpg",
    "author": "Ocean Blue Project, Inc.",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Oregon-beach-cleanup-ocean-blue-project-volunteers.jpg"
  },
  {
    "file": "File:Coastal-cleanup-month-ocean-blue-projects.jpg",
    "author": "Ocean Blue Project, Inc.",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Coastal-cleanup-month-ocean-blue-projects.jpg"
  },
  {
    "file": "File:Education-at-beach-cleanups-ocean-blue-project-oregon.jpg",
    "author": "Ocean Blue Project, Inc.",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Education-at-beach-cleanups-ocean-blue-project-oregon.jpg"
  },
  {
    "file": "File:Beach-cleanup-reusable-bags-no-plastic-bags-by-ocean-blue-project.jpg",
    "author": "Ocean Blue Project, Inc.",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Beach-cleanup-reusable-bags-no-plastic-bags-by-ocean-blue-project.jpg"
  },
  {
    "file": "File:Cracked earth - Flickr - Al Jazeera English.jpg",
    "author": "Al Jazeera English",
    "license": "CC BY-SA 2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Cracked_earth_-_Flickr_-_Al_Jazeera_English.jpg"
  },
  {
    "file": "File:Dry land (cracked) 7.jpg",
    "author": "Gannu03",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Dry_land_(cracked)_7.jpg"
  },
  {
    "file": "File:Drought land dry mud BOUHANIFIA Algeria 02.jpg",
    "author": "Hydrosami",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Drought_land_dry_mud_BOUHANIFIA_Algeria_02.jpg"
  },
  {
    "file": "File:Dry land (cracked) 6.jpg",
    "author": "Gannu03",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Dry_land_(cracked)_6.jpg"
  },
  {
    "file": "File:Drought land dry mud BOUHANIFIA Algeria.jpg",
    "author": "Hydrosami",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Drought_land_dry_mud_BOUHANIFIA_Algeria.jpg"
  },
  {
    "file": "File:Trees cut down for firewood purposes.jpg",
    "author": "Onyebuchi Echezona",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Trees_cut_down_for_firewood_purposes.jpg"
  },
  {
    "file": "File:Tree cut down.jpg",
    "author": "Onyebuchi Echezona",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Tree_cut_down.jpg"
  },
  {
    "file": "File:Trees cut down.jpg",
    "author": "Hope A Ncube",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Trees_cut_down.jpg"
  },
  {
    "file": "File:Tree been cut down.jpg",
    "author": "Iphone thirteen",
    "license": "CC0",
    "source": "https://commons.wikimedia.org/wiki/File:Tree_been_cut_down.jpg"
  },
  {
    "file": "File:Deforestation in Ghana (1).jpg",
    "author": "Apetigah Immaculate",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Deforestation_in_Ghana_(1).jpg"
  }
];
