"""Generate web/lib/credits.ts from backend/samples/public/CREDITS.md (T25)."""

import html
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CREDITS_MD = ROOT / "backend" / "samples" / "public" / "CREDITS.md"
OUT_TS = ROOT / "web" / "lib" / "credits.ts"

ANCHOR_RE = re.compile(r"<a\b[^>]*>(.*?)</a>", re.IGNORECASE | re.DOTALL)
HIDDEN_RE = re.compile(
    r"<(\w+)\b[^>]*display:\s*none[^>]*>.*?</\1>", re.IGNORECASE | re.DOTALL
)


def strip_html(text: str) -> str:
    text = HIDDEN_RE.sub("", text)
    text = ANCHOR_RE.sub(r"\1", text)
    text = re.sub(r"<[^>]+>", "", text)
    return html.unescape(text).strip()


def parse_rows(md: str) -> list[dict[str, str]]:
    rows = []
    for line in md.splitlines():
        line = line.strip()
        if not line.startswith("|") or line.startswith("|---"):
            continue
        cells = [c.strip() for c in line.strip("|").split("|")]
        if len(cells) != 4 or cells[0] == "File":
            continue
        file_, author, license_, source = cells
        rows.append(
            {
                "file": strip_html(file_),
                "author": strip_html(author),
                "license": strip_html(license_),
                "source": strip_html(source),
            }
        )
    return rows


def main() -> None:
    md = CREDITS_MD.read_text(encoding="utf-8")
    rows = parse_rows(md)
    body = json.dumps(rows, indent=2)
    OUT_TS.write_text(
        "// Generated by backend/scripts/generate_credits.py from "
        "backend/samples/public/CREDITS.md. Do not edit by hand.\n\n"
        "export type Credit = {\n"
        "  file: string;\n"
        "  author: string;\n"
        "  license: string;\n"
        "  source: string;\n"
        "};\n\n"
        f"export const CREDITS: Credit[] = {body};\n",
        encoding="utf-8",
    )
    print(f"Wrote {len(rows)} credits to {OUT_TS}")


if __name__ == "__main__":
    main()
